#!/usr/bin/env node
/**
 * Derech — seed the Israeli MFA transfer-permit FormTemplate.
 *
 * Reads the template JSON produced by the doc-engine workstream
 * (packages/doc-engine/templates/il-mfa-transfer-permit.json — the calibrated
 * coordinate map is authored THERE; this script never hardcodes coordinates)
 * and emits an idempotent upsert for public.form_templates.
 *
 * Usage:
 *   node seed/seed_form_template.mjs            # from burial-hub/db
 *   node seed_form_template.mjs                 # from burial-hub/db/seed
 *
 * Output:
 *   - prints the SQL to stdout
 *   - writes it next to this script as seed_form_template.sql
 *
 * Then paste/run the SQL in the Supabase SQL editor (after migrations 0001+).
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// db/seed -> up two levels to burial-hub/, then into packages/doc-engine
const TEMPLATE_PATH = path.resolve(
  __dirname,
  '..',
  '..',
  'packages',
  'doc-engine',
  'templates',
  'il-mfa-transfer-permit.json'
);

const OUT_PATH = path.resolve(__dirname, 'seed_form_template.sql');

let raw;
try {
  raw = readFileSync(TEMPLATE_PATH, 'utf8');
} catch (err) {
  if (err && err.code === 'ENOENT') {
    console.error(
      [
        'Template file not found:',
        `  ${TEMPLATE_PATH}`,
        '',
        'That file is produced by the doc-engine workstream',
        '(packages/doc-engine). It may not be built yet — re-run this script',
        'once packages/doc-engine/templates/il-mfa-transfer-permit.json exists.',
      ].join('\n')
    );
    process.exit(1);
  }
  throw err;
}

let tpl;
try {
  tpl = JSON.parse(raw);
} catch (err) {
  console.error(`Template file exists but is not valid JSON:\n  ${TEMPLATE_PATH}\n\n${err.message}`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Map the doc-engine template shape onto the form_templates columns.
// Be tolerant about optional keys; the coordinate payloads (pages/fields/
// grids/checks/bindings) are passed through verbatim as jsonb.
// ---------------------------------------------------------------------------

const key = tpl.key ?? 'il-mfa-transfer-permit';
const title = tpl.title ?? 'Israeli MFA — Body Transfer Permit';
const lang = tpl.lang ?? 'he';
const pdfPath = tpl.pdf_asset ?? tpl.pdf_path ?? null;
const pageWidth = tpl.page_width ?? tpl.pageWidth ?? tpl.pageSize?.width ?? tpl.pages?.[0]?.w ?? null;
const pageHeight = tpl.page_height ?? tpl.pageHeight ?? tpl.pageSize?.height ?? tpl.pages?.[0]?.h ?? null;
const pages = tpl.pages ?? [];
const fields = tpl.fields ?? [];
const grids = tpl.grids ?? [];
const checks = tpl.checks ?? [];
const bindings = tpl.bindings ?? {};
const version = Number.isInteger(tpl.version) ? tpl.version : 1;

if (!Array.isArray(fields) || fields.length === 0) {
  console.warn('WARNING: template has no fields[] — is the calibration done?');
}

// --- SQL literal helpers (standard_conforming_strings assumed ON) ----------

/** Escape a JS string as a single-quoted SQL literal. */
const sqlText = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);

/** Serialize a JS value as a jsonb literal. */
const sqlJsonb = (v) => `${sqlText(JSON.stringify(v))}::jsonb`;

/** Numeric or null. */
const sqlNum = (v) => (v === null || v === undefined || Number.isNaN(Number(v)) ? 'null' : String(Number(v)));

const sql = `-- Generated by seed/seed_form_template.mjs on ${new Date().toISOString()}
-- Source: packages/doc-engine/templates/il-mfa-transfer-permit.json
-- Do not edit by hand — recalibrate in the doc engine and regenerate.

insert into public.form_templates
  (key, title, lang, pdf_path, page_width, page_height,
   pages, fields, grids, checks, bindings, version, active)
values
  (${sqlText(key)},
   ${sqlText(title)},
   ${sqlText(lang)},
   ${sqlText(pdfPath)},
   ${sqlNum(pageWidth)},
   ${sqlNum(pageHeight)},
   ${sqlJsonb(pages)},
   ${sqlJsonb(fields)},
   ${sqlJsonb(grids)},
   ${sqlJsonb(checks)},
   ${sqlJsonb(bindings)},
   ${version},
   true)
on conflict (key) do update set
  title       = excluded.title,
  lang        = excluded.lang,
  pdf_path    = excluded.pdf_path,
  page_width  = excluded.page_width,
  page_height = excluded.page_height,
  pages       = excluded.pages,
  fields      = excluded.fields,
  grids       = excluded.grids,
  checks      = excluded.checks,
  bindings    = excluded.bindings,
  version     = excluded.version,
  active      = true;
`;

writeFileSync(OUT_PATH, sql, 'utf8');
console.log(sql);
console.error(`\nWrote ${OUT_PATH}`);
console.error('Run it in the Supabase SQL editor (after migrations).');
